Add jsgradient w/ npm auto-update
cdnjs/packages pull request #1352
Opened 2022-09-20 08:14 UTC by vishwas-r

2022-09-21 11:49 UTC, vishwas-r reviewed
Added auto-update

2022-10-01 22:48 UTC, MattIPv4 requested changes

2022-10-01 22:48 UTC, MattIPv4 commented on packages/j/jsgradient.json
> +  "name": "JSGradient",
```suggestion
  "name": "jsgradient",
```
This should match the filename being added, case-sensitive

2022-10-01 22:49 UTC, MattIPv4 approved these changes
LGTM

2022-10-01 22:49 UTC, merged