Add better-ajv-errors w/ npm auto-update
cdnjs/packages pull request #1722
Opened 2023-12-05 15:16 UTC by jeremyfiel

closes #1721

2023-12-06 02:30 UTC, MattIPv4 requested changes
🤔 It looks like you're including the cjs version here that uses Node.js `require` calls that won't work in a browser? Potentially we could add the ESM version for folks that're using modules, but ideally there'd be a pre-bundled browser version?

2023-12-06 02:40 UTC, jeremyfiel commented
Ya, all of these packages I added as a user.  So I don't have  any way to add the bundling.

2023-12-06 02:44 UTC, MattIPv4 commented
If this is switched over to the ESM version I'd be happy to add it for folks that're using browser modules, or consuming this through runtimes like Deno etc.

2023-12-06 02:46 UTC, jeremyfiel commented
Ok will update it

2023-12-06 04:39 UTC, jeremyfiel commented
ok, i think that glob pattern will work.  thanks

2024-01-07 21:56 UTC, MattIPv4 commented on packages/b/better-ajv-errors.json
> +          "/**/*.@(mjs?(.map))"
```suggestion
          "**/*.mjs?(.map)"
```

2024-01-07 21:57 UTC, MattIPv4 approved these changes

2024-01-07 21:57 UTC, merged