chore(carbon-charts): add @carbon/charts to CDNJS
cdnjs/packages pull request #1732
Opened 2023-12-26 15:32 UTC by nstuyvesant

2023-12-28 00:57 UTC, nstuyvesant reviewed
Sorry I left out the extension.

2024-01-07 22:04 UTC, MattIPv4 requested changes

2024-01-07 22:04 UTC, MattIPv4 commented on packages/c/carbon-charts.json
> +          "**/*.css.map"
```suggestion
          "*.css?(.map)"
```
You can combine this into a single glob, and I don't believe you need a glob star here, as the CSS files aren't in nested folders?

2024-01-07 22:04 UTC, MattIPv4 commented on packages/c/carbon-charts.json
> +          "**/*.@(js|map)"
```suggestion
          "*.js?(.map)"
```
Same deal here?

2024-01-07 22:04 UTC, MattIPv4 commented on packages/c/carbon-charts.json
> +  "filename": "dist/umd/bundle.umd.js",
```suggestion
  "filename": "bundle.umd.js",
```
As you're setting `basePath`, we'll pull files up out of that directory

2024-02-04 22:06 UTC, MattIPv4 approved these changes
LGTM

2024-02-04 22:06 UTC, merged