Add erc725.js w/ npm auto-update
cdnjs/packages pull request #1827
Opened 2024-06-21 07:31 UTC by CJ42

https://www.npmjs.com/package/@erc725/erc725.js

2024-06-21 08:00 UTC, magalimorin18 approved these changes
good idea

2024-07-17 09:45 UTC, MattIPv4 requested changes

2024-07-17 09:45 UTC, MattIPv4 commented on packages/e/erc725js.json
> +        "basePath": "",
```suggestion
        "basePath": "build/main/src",
```
The files under `build/main/src` make use of Node.js `require` calls and will not work in a browser. As such, I suspect you just want the files from `build/module/src`, which should work in browsers that support ESM.

2024-07-17 09:45 UTC, MattIPv4 commented on packages/e/erc725js.json
> +          "**/*.@(js|ts)"
```suggestion
          "**/*.@(js|d.ts)"
```

2024-07-17 09:45 UTC, MattIPv4 commented on packages/e/erc725js.json
> +  "filename": "erc725.min.js",
```suggestion
  "filename": "index.min.js",
```
It looks like the entrypoint file for the library is `index.js` (or `index.min.js` that we'll generate), not `erc725.min.js`

2024-08-04 15:12 UTC, MattIPv4 commented on packages/e/erc725js.json
> +        "basePath": "build/main/src",
```suggestion
        "basePath": "build/module/src",
```
The `main` build appears to make use of Node.js `require` calls that will not work in a browser. The `module` version appears to use `import` statements which should work for folks using ESM in the browser.

2024-08-04 15:14 UTC, MattIPv4 approved these changes
LGTM

2024-08-04 15:14 UTC, merged