Add surreal w/ git auto-update
cdnjs/packages pull request #1830
Opened 2024-06-26 06:10 UTC by jph00

Adding Surreal.js library to cdnjs. 

- Library: https://github.com/gnat/surreal/
- Auto-update configured for git
- Files to be included: surreal.js, surreal.min.js

2024-07-17 18:25 UTC, jph00 commented
Thanks @MattIPv4 -- sorry about that. Should be fixed now.

2024-08-04 15:16 UTC, MattIPv4 requested changes

2024-08-04 15:16 UTC, MattIPv4 commented on packages/s/surreal.json
> +    "target": "git://github.com/answerdotai/surreal.git",
I'm not sure I'm a fan of using a fork of the source repository as the auto-update target here, as there is no guarantee the source code isn't being tampered with (I even see a commit in the repo that does modify the source). Please work with the original author to have it tagged or published to NPM instead.

2024-08-04 22:46 UTC, jph00 commented
I've checked with @gnat, and he feels that the approach of pulling from my fork is preferred. He does not want to tag releases in the main project, in order to avoid implicitly encouraging the use of build machinery.

2024-08-11 19:03 UTC, MattIPv4 commented
Given the context in https://github.com/cdnjs/packages/pull/1831#issuecomment-2267849805, I'm happy to let this through with the different source.

2024-08-11 19:03 UTC, MattIPv4 approved these changes
LGTM

2024-08-11 19:03 UTC, merged