Add css-scope-inline w/ git auto-update
cdnjs/packages pull request #1831
Opened 2024-06-26 06:18 UTC by jph00

Adding CSS Scope Inline library to cdnjs. 

- Library: https://github.com/gnat/css-scope-inline
- Auto-update configured for git
- Files to be included: script.js

2024-07-17 10:43 UTC, MattIPv4 requested changes
As the CI error indicates, to pull from a GitHub repository, there needs to be tags for each version that we should pull into cdnjs.

2024-07-17 18:34 UTC, jph00 commented
This should be fixed now too.

2024-08-04 15:17 UTC, MattIPv4 requested changes

2024-08-04 15:17 UTC, MattIPv4 commented on packages/c/css-scope-inline.json
> +    "target": "git://github.com/answerdotai/css-scope-inline.git",
As with #1830, I am not comfortable using a fork of the source repository as the auto-update target here, as there is no guarantee the source code isn't being tampered with. Please work with the original author to have it tagged or published to NPM instead.

2024-08-04 21:53 UTC, jph00 commented
Understood @MattIPv4 -- I reached out to the author once already since I also felt that would be preferred, but didn't get a response. I've actually set up an automatic release github workflow on the fork which pulls directly from the source repo. AFAICT there's no particular reason to believe the source repo would be less likely to have sketchy stuff going on than my version!

If I'm not able to get a response from the original author, what could I do to create a new project based on the original which you'd be comfortable adding to cdnjs? Would I need to give it a new name? In general I assume there's a way for project forks to be added to cdnjs -- quite often forks become more popular than the originals?

2024-08-04 22:50 UTC, gnat commented
Hey @MattIPv4 , I'm the author of both of these libraries.

In this specific case, I feel the fork is OK for cdnjs, because:

* I do not plan to add tagged releases to either project, specifically because I do not want to railroad new developers into thinking they need to use build machinery.
  * One of the main goals of these projects is to service new developers, to be real legit examples of libraries you can just download or copy/paste to work.
* Both projects currently have CDN hosted on https://www.jsdelivr.com
  * I explicitly chose jsdelivr because no tagging is required.
  * Unless there's a downside to jsdelivr I'm not considering??
* @jph00 requires the use of cdnjs because of a commercial product that only supports cdnjs.
  * I do not plan to add build machinery just to accommodate the commercial entity- they could add jsdelivr tomorrow and this conversation is moot.

Part of the whole idea behind surreal, css-scope-inline (and IMHO, htmx) is they are useful projects you can just paste the script in and have it work without new developers feeling like they are being railroaded into a toolchain pipeline, which often distracts and clouds their understanding and make them a captive audience to that machinery.

Apologies for dragging you into this. I understand we all have limited bandwidth to make workarounds for private companies.

2024-08-11 19:02 UTC, MattIPv4 commented
Understood, thank you for the context! Given that, I'll let this go through with the different source repo.

2024-08-11 19:02 UTC, MattIPv4 approved these changes
LGTM

2024-08-11 19:02 UTC, merged

2024-08-13 06:24 UTC, jph00 commented
@MattIPv4 thanks for your help. Question: surreal.js is showing up in the cdn, but this one (css-scope-inline) isn't-- does it just take a while?

2024-08-13 19:18 UTC, jph00 commented
Apologies, I figured out the source of the problem - pebkac... Made a PR to fix.