Update sip.js.json
cdnjs/packages pull request #431
Opened 2020-09-08 13:17 UTC by james-criscuolo

We've updated our dist folder from `dist` to `lib` since moving to typescript, and the initial file to pull is now `index.js` there instead of `sip.min.js`

2020-09-11 11:37 UTC, MattIPv4 requested changes
`lib/index.js` is a Node.js file that uses require. This will not work in the context of a browser. The old `dist/sip.min.js` file was a prebundled version, which is what's needed to work in a browser.

2020-09-11 13:37 UTC, james-criscuolo commented
Sorry for this mistake. We stopped publishing our bundles via NPM, and now only have them in git. It appears I can switch to git based in my json file, but I don't see anything in the documentation (or other libraries using git) of not using the master branch. Our bundles live on the release branch in the `dist` folder, here: https://github.com/onsip/SIP.js/tree/release

Is it possible to declare a branch in the json file?

2020-09-11 13:39 UTC, MattIPv4 commented
@tc80 do we check out the tag directly when getting versions from git? If so, then a branch setting isn't needed as a tag is always tied to a specific branch/commit

2020-09-11 13:43 UTC, james-criscuolo commented
Our tags do point to that branch, so we would be ok there too, assuming it just takes the latest tag?

2020-09-11 13:44 UTC, MattIPv4 commented
Yeah, we work based on tags for git auto-update. If you update this PR to use git auto-update, the CI will test if its working as expected or not.

2020-09-11 13:55 UTC, tc80 commented
> @tc80 do we check out the tag directly when getting versions from git? If so, then a branch setting isn't needed as a tag is always tied to a specific branch/commit

```// ForceCheckout force checkouts a particular tag.
func ForceCheckout(ctx context.Context, gitpath, tag string) {
	args := []string{"checkout", tag, "-f"}

	cmd := exec.Command("git", args...)
	cmd.Dir = gitpath
	util.Debugf(ctx, "run %s\n", cmd)
	util.CheckCmd(cmd.CombinedOutput())
}```

Looks to me like we check out the tag directly. Should be ok! 👍

2020-09-20 19:08 UTC, MattIPv4 approved these changes
Lgtm - thank you! :)

2020-09-20 19:09 UTC, merged