Add otpauth w/ git auto-update
cdnjs/packages pull request #436
Opened 2020-09-11 18:54 UTC by hectorm

2020-09-11 19:06 UTC, hectorm commented
Although the project on GitHub has less than 200 stars, it currently receives 34k downloads per month in [npm](https://www.npmjs.com/package/otpauth). But I prefer to add it as a git repository instead of npm. If this is a problem, I can change it to npm.

2020-09-20 19:15 UTC, MattIPv4 requested changes

2020-09-20 19:15 UTC, MattIPv4 commented on packages/o/otpauth.json
> +      }
```suggestion
      {
        "basePath": "dist",
        "files": [
          "*.js?(.map)"
        ]
      },
      {
        "basePath": "types",
        "files": [
          "*.d.ts"
        ]
      }
```
Let's pull the files out of their subdirectories to the root directory when they're on cdnjs, for simplicity.

2020-09-20 19:15 UTC, MattIPv4 commented on packages/o/otpauth.json
> +  "filename": "dist/otpauth.cjs.min.js",
```suggestion
  "filename": "otpauth.cjs.min.js",
```
Per other suggestion, let's pull this out to the root.

2020-09-21 20:23 UTC, hectorm commented
I've commited the suggestions.

2020-09-23 10:23 UTC, MattIPv4 approved these changes
Lgtm, thank you!

2020-09-23 10:24 UTC, merged