Adding ZzFX w/ git auto-update
cdnjs/packages pull request #484
Opened 2020-10-31 18:45 UTC by jdnichollsc

2020-11-02 11:23 UTC, MattIPv4 requested changes

2020-11-02 11:23 UTC, MattIPv4 commented on packages/z/ZzFX.json
> +          "ZzFX.js"
```suggestion
          "ZzFX.*.js"
```
Let's just include all versions

2020-11-02 14:01 UTC, jdnichollsc commented on packages/z/ZzFX.json
> +          "ZzFX.js"
Done, thanks for your correction!

2020-11-03 14:54 UTC, jdnichollsc commented
@MattIPv4 what do you think about the last change? Thanks!

2020-11-03 15:03 UTC, MattIPv4 commented
Will take a look at it when I have some time 👍

2020-11-03 15:11 UTC, jdnichollsc commented
Thanks for your help! <3

2020-11-08 17:26 UTC, MattIPv4 requested changes

2020-11-08 17:26 UTC, MattIPv4 commented on packages/z/ZzFX.json
> +          "ZzFX.*.js"
```suggestion
          "ZzFX?(.*).js"
```
Make extra period + part optional

2020-11-08 17:43 UTC, MattIPv4 approved these changes
Lgtm

2020-11-08 17:45 UTC, merged