Add statosio.js to packages
cdnjs/packages pull request #517
Opened 2020-11-25 04:05 UTC by a6b8

Statosio.js is an add-on function for d3.js to generate simple chart diagrams, in a fast and reliable way.

https://d3.statosio.com

2020-11-29 13:20 UTC, MattIPv4 requested changes
Please fix the issues the CI is raising

2020-11-29 22:54 UTC, a6b8 commented
> Please fix the issues the CI is raising

Error was: "no tagged version found in git"

I created a release with a version tag. should working now.

2020-12-02 21:18 UTC, MattIPv4 requested changes

2020-12-02 21:18 UTC, MattIPv4 commented on packages/s/statosio.json
> +  "name": "statosio.js",
```suggestion
  "name": "statosio",
```
Match filename

2020-12-02 21:18 UTC, MattIPv4 commented on packages/s/statosio.json
> +        "url": "13plus4.com"
```suggestion
      "name": "Andreas Banholzer",
      "email": "hello@13plus4.com",
      "url": "13plus4.com"
```
Correct 2-space indentation

2020-12-02 21:18 UTC, MattIPv4 commented on packages/s/statosio.json
> +          "**/*"
```suggestion
          "*.js"
```
Open wildcards are dangerous, let's restrict this

2020-12-06 14:20 UTC, MattIPv4 approved these changes
Lgtm, ty

2020-12-06 14:20 UTC, merged