Add iosevka w/ git auto-update
cdnjs/packages pull request #705
Opened 2021-04-22 01:53 UTC by aymanbagabas

Use the mirror https://github.com/aymanbagabas/iosevka-fonts instead of https://github.com/be5invis/Iosevka to distribute the fonts.

2021-04-22 05:59 UTC, alexeyten commented on packages/i/Iosevka.json
> +        "files": ["*/*.css", "*/*/.(ttf|woff2)"]
Shouldn't it be `*/*/*.(ttf|woff2)`?

2021-04-22 08:06 UTC, MattIPv4 requested changes
I am very hesitant to accept a PR where the target for auto-updating is known to not be the true source -- there is no history to demonstrate that this source can be trusted, you could easily publish files that are not in the true source.

2021-04-22 14:10 UTC, aymanbagabas commented
> I am very hesitant to accept a PR where the target for auto-updating is known to not be the true source -- there is no history to demonstrate that this source can be trusted, you could easily publish files that are not in the true source.

I totally agree. This is related to https://github.com/be5invis/Iosevka/issues/942. The reason for this is that the author refused to maintain the files in the main repository.

2021-04-25 23:10 UTC, MattIPv4 approved these changes
Lgtm, seems the original maintainer is okay with this.

2021-04-25 23:11 UTC, merged