Add tooltip.css
cdnjs/packages pull request #768
Opened 2021-07-05 07:04 UTC by tiagorangel2011

Hi! Remember to add tooltip.css to the list of packages.

2021-07-05 21:35 UTC, MattIPv4 requested changes

2021-07-05 21:35 UTC, MattIPv4 commented on packages/t/tooltipcss.json
> +    "url": "https://github.com/tiagorangel2011.git"
This is not a valid git repository

2021-07-05 21:35 UTC, MattIPv4 commented on packages/t/tooltipcss.json
> +  "license": "Creative Commons - Attribution-NoDerivatives 4.0 International",
This is not a valid SPDX identifier

2021-07-05 21:35 UTC, MattIPv4 commented on packages/t/tooltipcss.json
> +    "target": "git://github.com/tiagorangel2011.git",
This is not a valid git repository

2021-07-12 07:15 UTC, tiagorangel2011 commented on packages/t/tooltipcss.json
> +    "url": "https://github.com/tiagorangel2011.git"
Oh, sorry

2021-07-17 11:45 UTC, MattIPv4 commented
No progress, closing

2021-07-17 11:45 UTC, closed without merging