Create Citation.js
cdnjs/packages pull request #810
Opened 2021-07-29 00:24 UTC by jonlandrum

This addition adds support for [Citation.js](https://citation.js.org/).

2021-07-29 00:25 UTC, jonlandrum commented
Closes #808.

2021-07-29 08:40 UTC, MattIPv4 requested changes
1. Your file should be a `.json` file
2. The contents are not currently valid JSON
3. The file needs more than just the auto-update definition

I recommend taking a look at other recent PRs that have been merged for what exactly you should be including.

2021-08-03 22:05 UTC, MattIPv4 commented
No progress, closing.

2021-08-03 22:05 UTC, closed without merging

2021-08-05 14:34 UTC, jonlandrum commented
@MattIPv4 sorry about the radio silence; it's been a crazy week at work. I saw you finished the rest of the changes to make a proper merge. I'd like to make a PR for updating the directions for contributors, as I believe I was just following the directions there as for what was required for a complete addition of a new package.

2021-08-05 14:54 UTC, MattIPv4 commented
👍 The contributing guide only covers specific information on the auto-update config in a package, not the full package file. A PR that adds a new section covering a package config file more generally would be great! The full schema is here for reference: https://github.com/cdnjs/tools/blob/master/schema_human.json